# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 24
  dof_obs_size: 23
  actions_dim: 23
  lower_body_actions_dim: 13
  upper_body_actions_dim: 10
  policy_obs_dim: -1
  critic_obs_dim: -1

  key_bodies: ["left_ankle_roll_link", "right_ankle_roll_link"]
  contact_bodies: [ "left_ankle_roll_link", "right_ankle_roll_link" ]
  num_feet: 2
  right_foot_name: "right_ankle_roll_link"
  left_foot_name: "left_ankle_roll_link"
  foot_name: "ankle_roll_link"
  knee_name: "knee_link"
  has_torso: True
  torso_name: "torso_link"
  has_upper_body_dof: True
  dof_names: ['left_thigh_pitch_joint', 'left_thigh_roll_joint', 'left_thigh_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
              'right_thigh_pitch_joint', 'right_thigh_roll_joint', 'right_thigh_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint',
              'torso_joint',
              'left_arm_pitch_joint', 'left_arm_roll_joint', 'left_arm_yaw_joint', 'left_elbow_pitch_joint', 'left_elbow_yaw_joint', 
              'right_arm_pitch_joint', 'right_arm_roll_joint', 'right_arm_yaw_joint', 'right_elbow_pitch_joint', 'right_elbow_yaw_joint']
  upper_dof_names: ['left_arm_pitch_joint', 'left_arm_roll_joint', 'left_arm_yaw_joint', 'left_elbow_pitch_joint', 'left_elbow_yaw_joint',
                    'right_arm_pitch_joint', 'right_arm_roll_joint', 'right_arm_yaw_joint', 'right_elbow_pitch_joint', 'right_elbow_yaw_joint']
  upper_left_arm_dof_names: ['left_arm_pitch_joint', 'left_arm_roll_joint', 'left_arm_yaw_joint', 'left_elbow_pitch_joint', 'left_elbow_yaw_joint']
  upper_right_arm_dof_names: ['right_arm_pitch_joint', 'right_arm_roll_joint', 'right_arm_yaw_joint', 'right_elbow_pitch_joint', 'right_elbow_yaw_joint']
  lower_dof_names: ['left_thigh_pitch_joint', 'left_thigh_roll_joint', 'left_thigh_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
                    'right_thigh_pitch_joint', 'right_thigh_roll_joint', 'right_thigh_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint',
                    'torso_joint']
  waist_dof_names: ['torso_joint']
  dof_pos_lower_limit_list: [-2.5307, -0.5236, -2.7576, -0.087267, -0.87267, -0.2618, 
                             -2.5307, -2.9671, -2.7576, -0.087267, -0.87267, -0.2618, 
                             -2.618, -0.52, -0.52,
                             -3.0892, -1.5882, -2.618, -1.0472, 
                             -3.0892, -2.2515, -2.618, -1.0472]
  dof_pos_upper_limit_list: [2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618, 
                             2.8798, 0.5236, 2.7576, 2.8798, 0.5236, 0.2618, 
                             2.618, 0.52, 0.52,
                             2.6704, 2.2515, 2.618, 2.0944,
                             2.6704, 1.5882, 2.618, 2.0944]
  dof_vel_limit_list: [32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 
                       32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 
                       32.0, 37.0, 37.0, 
                       37.0, 37.0, 37.0, 37.0, 
                       37.0, 37.0, 37.0, 37.0]
  dof_effort_limit_list: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                          88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                          88.0, 50.0, 50.0,
                          25.0, 25.0, 25.0, 25.0, 
                          25.0, 25.0, 25.0, 25.0]
  
  # only apply for isaacsim
  dof_armature_list: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03, 0.03,
                      0.04, 0.03, 0.03, 0.03]
  # only apply for isaacsim
  dof_joint_friction_list: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03]

  body_names: ['base_link', 
                'left_thigh_pitch_link', 'left_thigh_roll_link', 'left_thigh_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link',
                'right_thigh_pitch_link', 'right_thigh_roll_link', 'right_thigh_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link',
                'torso_link',
                'left_arm_pitch_link', 'left_arm_roll_link', 'left_arm_yaw_link', 'left_elbow_pitch_link', 'left_elbow_yaw_link',
                'right_arm_pitch_link', 'right_arm_roll_link', 'right_arm_yaw_link', 'right_elbow_pitch_link', 'right_elbow_yaw_link']


  terminate_after_contacts_on : ["base_link", "arm", "thigh"]
  penalize_contacts_on: ["base_link", "arm", "thigh"]
  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_thigh_pitch_joint: -0.1
      left_thigh_roll_joint: 0.
      left_thigh_yaw_joint: 0.
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.
      right_thigh_pitch_joint: -0.1
      right_thigh_roll_joint: 0.
      right_thigh_yaw_joint: 0.
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.
      torso_joint : 0.
      left_arm_pitch_joint: 0.
      left_arm_roll_joint: 0.
      left_arm_yaw_joint: 0.
      left_elbow_joint: 0.
      right_arm_pitch_joint: 0.
      right_arm_roll_joint: 0.
      right_arm_yaw_joint: 0.
      right_elbow_joint: 0.



  randomize_link_body_names: [
    'base_link', 'left_thigh_yaw_link', 'left_thigh_roll_link', 'left_thigh_pitch_link', 'left_knee_link',
    'right_thigh_yaw_link', 'right_thigh_roll_link', 'right_thigh_pitch_link', 'right_knee_link',
  ]

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      thigh_yaw: 100
      thigh_roll: 100
      thigh_pitch: 100
      knee: 200
      ankle_pitch: 20
      ankle_roll: 20
      torso: 400
      arm_pitch: 90
      arm_roll: 60
      arm_yaw: 20
      elbow: 60


    damping: # [N*m/rad]  # [N*m*s/rad]
      thigh_yaw: 2.5
      thigh_roll: 2.5
      thigh_pitch: 2.5
      knee: 5.0
      ankle_pitch: 0.2
      ankle_roll: 0.1
      torso: 5.0
      arm_pitch: 2.0
      arm_roll: 1.0
      arm_yaw: 0.4
      elbow: 1.0

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "atom01/${robot.asset.robot_type}.urdf"
    usd_file: "atom01/${robot.asset.robot_type}.usd"
    xml_file: "atom01/${robot.asset.robot_type}.xml"
    robot_type: atom01
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

    fix_base_link: False # TEST: fix base link to world

  motion:
    motion_file : 'humanoidverse/data/motions/g1_29dof_anneal_23dof/v1/amass_all.pkl'
    asset:
      assetRoot: "humanoidverse/data/robots/atom01/"
      assetFileName: "atom01.xml"
      urdfFileName: "atom01.urdf"

    humanoid_type: atom01
    bias_offset: False
    has_self_collision: True
    has_mesh: False
    has_jt_limit: False
    has_dof_subset: True
    has_upright_start: True
    has_smpl_pd_offset: False
    remove_toe: False # For humanoid's geom toe
    motion_sym_loss: False
    sym_loss_coef: 1
    big_ankle: True

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: False

    masterfoot: False
    freeze_toe: false
    freeze_hand: False
    box_body: True
    real_weight: True
    real_weight_porpotion_capsules: True
    real_weight_porpotion_boxes: True

    body_names: ['base_link', 
                 'left_thigh_pitch_link', 'left_thigh_roll_link', 'left_thigh_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link', 
                 'right_thigh_pitch_link', 'right_thigh_roll_link', 'right_thigh_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link', 
                 'torso_link',
                 'left_arm_pitch_link', 'left_arm_roll_link', 'left_arm_yaw_link', 'left_elbow_pitch_link', 'left_elbow_yaw_link',
                 'right_arm_pitch_link', 'right_arm_roll_link', 'right_arm_yaw_link', 'right_elbow_pitch_link', 'right_elbow_yaw_link']
          
    limb_weight_group: 
      - ['left_thigh_pitch_link', 'left_thigh_roll_link', 'left_thigh_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link']
      - ['right_thigh_pitch_link', 'right_thigh_roll_link', 'right_thigh_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link']
      - ['base_link', 'torso_link']
      - ['left_arm_pitch_link', 'left_arm_roll_link', 'left_arm_yaw_link', 'left_elbow_pitch_link', 'left_elbow_yaw_link']
      - ['right_arm_pitch_link', 'right_arm_roll_link', 'right_arm_yaw_link', 'right_elbow_pitch_link', 'right_elbow_yaw_link']

    dof_names: ['left_thigh_pitch_link', 'left_thigh_roll_link', 'left_thigh_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link', 
                'right_thigh_pitch_link', 'right_thigh_roll_link', 'right_thigh_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link', 
                'torso_link',
                'left_arm_pitch_link', 'left_arm_roll_link', 'left_arm_yaw_link', 'left_elbow_pitch_link', 'left_elbow_yaw_link',
                'right_arm_pitch_link', 'right_arm_roll_link', 'right_arm_yaw_link', 'right_elbow_pitch_link', 'right_elbow_yaw_link']


    nums_extend_bodies: 13
    extend_config:
      - joint_name: "left_hand_link"
        parent_name: "left_elbow_yaw_link"
        pos: [0.23, -0.03, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_hand_link"
        parent_name: "right_elbow_yaw_link"
        pos: [0.23, 0.03, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "left_elbow_link"
        parent_name: "left_elbow_yaw_link"
        pos: [-0.05, -0.03, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_elbow_link"
        parent_name: "right_elbow_yaw_link"
        pos: [-0.05, 0.03, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "left_knee_link_"
        parent_name: "left_knee_link"
        pos: [0.0, -0.02, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_knee_link_"
        parent_name: "right_knee_link"
        pos: [0.0, 0.02, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "left_thigh_link"
        parent_name: "left_thigh_yaw_link"
        pos: [0.04, -0.035, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_thigh_link"
        parent_name: "right_thigh_yaw_link"
        pos: [0.04, 0.035, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "head_link"
        parent_name: "torso_link"
        pos: [0.0, 0.0, 0.32]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "left_toe_link"
        parent_name: "left_ankle_roll_link"
        pos: [0.1, 0.0, -0.035]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_toe_link"
        parent_name: "right_ankle_roll_link"
        pos: [0.1, 0.0, -0.035]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "left_arm_link"
        parent_name: "left_arm_yaw_link"
        pos: [0.0, 0.0, 0.05]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_arm_link"
        parent_name: "right_arm_yaw_link"
        pos: [0.0, 0.0, 0.05]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z

    motion_tracking_link:
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"

    lower_body_link:
      - "base_link"
      - "left_thigh_pitch_link"
      - "left_thigh_roll_link"
      - "left_thigh_yaw_link"
      - "left_knee_link"
      - "left_ankle_pitch_link"
      - "left_ankle_roll_link"
      - "right_thigh_pitch_link"
      - "right_thigh_roll_link"
      - "right_thigh_yaw_link"
      - "right_knee_link"
      - "right_ankle_pitch_link"
      - "right_ankle_roll_link"
      - "torso_link"
      - "left_knee_link_"
      - "right_knee_link_"
      - "left_thigh_link"
      - "right_thigh_link"
      - "pelvis_link"
      - "left_toe_link"
      - "right_toe_link"

    upper_body_link:
      - "left_arm_pitch_link"
      - "left_arm_roll_link"
      - "left_arm_yaw_link"
      - "left_elbow_pitch_link"
      - "left_elbow_yaw_link"
      - "right_arm_pitch_link"
      - "right_arm_roll_link"
      - "right_arm_yaw_link"
      - "right_elbow_pitch_link"
      - "right_elbow_yaw_link"
      - "left_hand_link"
      - "right_hand_link"
      - "left_elbow_link"
      - "right_elbow_link"
      - "head_link"
      - "left_arm_link"
      - "right_arm_link"


    pelvis_link: "base_link"
    base_link: "torso_link"
    hips_link:
      - "left_thigh_pitch_link"
      - "left_thigh_roll_link"
      - "left_thigh_yaw_link"
      - "right_thigh_pitch_link"
      - "right_thigh_roll_link"
      - "right_thigh_yaw_link"
      - "left_thigh_link"
      - "right_thigh_link"
    
    joint_matches:
      - ["base_link", "Pelvis"]
      - ["left_thigh_link", "L_Hip"]
      - ["left_knee_link_", "L_Knee"]
      - ["left_ankle_roll_link", "L_Ankle"]
      - ["right_thigh_link", "R_Hip"]
      - ["right_knee_link_", "R_Knee"]
      - ["right_ankle_roll_link", "R_Ankle"]
      - ["left_arm_link", "L_Shoulder"]
      - ["left_elbow_link", "L_Elbow"]
      - ["left_hand_link", "L_Hand"]
      - ["right_arm_link", "R_Shoulder"]
      - ["right_elbow_link", "R_Elbow"]
      - ["right_hand_link", "R_Hand"]
      - ["head_link", "Head"]
      - ["left_toe_link", "L_Toe"]
      - ["right_toe_link", "R_Toe"]

    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"
      - L_Elbow: "[0, -np.pi/2, 0]"
      - R_Elbow: "[0, np.pi/2, 0]"

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0.929, 0.867, 0.437] # base_link
      - [0.929, 0.867, 0.437] # left_thigh_yaw_joint
      - [0.929, 0.867, 0.437] # left_thigh_roll_joint
      - [0.929, 0.867, 0.437] # left_thigh_pitch_joint
      - [0.929, 0.867, 0.437] # left_knee_joint
      - [0.929, 0.867, 0.437] # left_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # left_ankle_roll_joint
      - [0.929, 0.867, 0.437] # right_thigh_yaw_joint
      - [0.929, 0.867, 0.437] # right_thigh_roll_joint
      - [0.929, 0.867, 0.437] # right_thigh_pitch_joint
      - [0.929, 0.867, 0.437] # right_knee_joint
      - [0.929, 0.867, 0.437] # right_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # right_ankle_roll_joint
      - [0.929, 0.867, 0.437] # torso_joint
      - [0.929, 0.867, 0.437] # left_arm_pitch_joint
      - [0.929, 0.867, 0.437] # left_arm_roll_joint
      - [0.929, 0.867, 0.437] # left_arm_yaw_joint
      - [0.929, 0.867, 0.437] # left_elbow_joint
      - [0.929, 0.867, 0.437] # right_arm_pitch_joint
      - [0.929, 0.867, 0.437] # right_arm_roll_joint
      - [0.929, 0.867, 0.437] # right_arm_yaw_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0, 0.351, 0.613] # left_elbow_joint_extend
      - [0, 0.351, 0.613] # right_elbow_joint_extend
      - [0, 0.351, 0.613] # neck_link

